# Generated by Django 3.1.3 on 2021-02-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_ip_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='os',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
