# Generated by Django 3.1.3 on 2021-02-05 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='commentPermit',
            field=models.ManyToManyField(related_name='commentpermit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='showPermit',
            field=models.ManyToManyField(related_name='showpermit', to=settings.AUTH_USER_MODEL),
        ),
    ]
