# Generated by Django 3.1.3 on 2021-02-07 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210207_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='os',
            field=models.CharField(default='no', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ip',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
