# Generated by Django 3.1.3 on 2021-02-07 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210207_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip_address',
            field=models.GenericIPAddressField(default=django.utils.timezone.now),
        ),
    ]
