# Generated by Django 3.1.3 on 2021-02-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210207_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='ip',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
