# Generated by Django 3.1.3 on 2021-02-08 14:08

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210207_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_expired',
            field=models.DateTimeField(default=account.models.get_default_my_date),
        ),
    ]
